notifications:
  webhooks:
    - https://webhook.commit-email.info/

matrix:
  include:
    - name: Ruby 2.4
      rvm: 2.4
    - name: Ruby 2.5
      rvm: 2.5
    - name: Ruby 2.6
      rvm: 2.6
    - name: macOS
      os: osx
      rvm: 2.6
      before_install:
        - brew bundle
